services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - microservice_auth
      - microservice_cliente
      - microservice_pedido
    networks:
      - microservices_network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices_network

  microservice_auth:
    build: ./microservice_auth
    ports:
      - "4004:5000"
    networks:
      - microservices_network

  microservice_cliente:
    build: ./microservice_cliente
    ports:
      - "4002:5000"
    networks:
      - microservices_network

  microservice_pedido:
    build: ./microservice_pedido
    ports:
      - "4001:5000"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
