services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - microservice_auth
      - microservice_cliente
      - microservice_pedido
    networks:
      - microservices_network

  microservice_auth:
    build: ./microservice_auth
    ports:
      - "4004:5000"
    networks:
      - microservices_network

  microservice_cliente:
    build: ./microservice_cliente
    ports:
      - "4002:5000"
    networks:
      - microservices_network

  microservice_pedido:
    build: ./microservice_pedido
    ports:
      - "4001:5000"
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge
